import { NextPage } from 'next'
import Head from 'next/head'

import { BookSection } from '../components/bookSection'

const Home: NextPage = function () {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BookSection />
      </main>
    </div>
  )
}

export default Home
